#!/usr/bin/env node
// Reads .env and writes js/config.js
// Run: node scripts/gen-config.js

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

function parseEnv(text) {
    const env = {};
    for (const line of text.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq === -1) continue;
        env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
    }
    return env;
}

const env = parseEnv(readFileSync(resolve(root, '.env'), 'utf8'));

const required = [
    'CLOUDINARY_CLOUD_NAME', 'CLOUDINARY_UPLOAD_PRESET',
    'FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_DATABASE_URL',
    'FIREBASE_PROJECT_ID', 'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID',
];

const missing = required.filter(k => !env[k]);
if (missing.length) {
    console.error('Missing required .env keys:', missing.join(', '));
    process.exit(1);
}

const config = `// Auto-generated by scripts/gen-config.js — do not edit directly.
// Edit .env, then run: node scripts/gen-config.js

export const FIREBASE_CONFIG = {
    apiKey:            "${env.FIREBASE_API_KEY}",
    authDomain:        "${env.FIREBASE_AUTH_DOMAIN}",
    databaseURL:       "${env.FIREBASE_DATABASE_URL}",
    projectId:         "${env.FIREBASE_PROJECT_ID}",
    storageBucket:     "${env.FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${env.FIREBASE_MESSAGING_SENDER_ID}",
    appId:             "${env.FIREBASE_APP_ID}"
};

export const CLOUDINARY_CLOUD_NAME    = "${env.CLOUDINARY_CLOUD_NAME}";
export const CLOUDINARY_UPLOAD_PRESET = "${env.CLOUDINARY_UPLOAD_PRESET}";
`;

writeFileSync(resolve(root, 'js/config.js'), config);
console.log('js/config.js generated from .env');
